/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// RouteFilterRuleState : Route Filter Rule status
type RouteFilterRuleState string

// List of RouteFilterRuleState
const (
	PROVISIONING_RouteFilterRuleState      RouteFilterRuleState = "PROVISIONING"
	REPROVISIONING_RouteFilterRuleState    RouteFilterRuleState = "REPROVISIONING"
	DEPROVISIONING_RouteFilterRuleState    RouteFilterRuleState = "DEPROVISIONING"
	PROVISIONED_RouteFilterRuleState       RouteFilterRuleState = "PROVISIONED"
	DEPROVISIONED_RouteFilterRuleState     RouteFilterRuleState = "DEPROVISIONED"
	NOT_PROVISIONED_RouteFilterRuleState   RouteFilterRuleState = "NOT_PROVISIONED"
	NOT_DEPROVISIONED_RouteFilterRuleState RouteFilterRuleState = "NOT_DEPROVISIONED"
)
