/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

type RouteFilterRulesData struct {
	// Route Filter Rules URI
	Href string `json:"href,omitempty"`
	// Route Filter type
	Type_ string `json:"type,omitempty"`
	// Route Filter Rule identifier
	Uuid string `json:"uuid,omitempty"`
	Name string `json:"name,omitempty"`
	// Customer-provided Route Filter Rule description
	Description string                `json:"description,omitempty"`
	State       *RouteFilterRuleState `json:"state,omitempty"`
	// prefix matching operator
	PrefixMatch string                  `json:"prefixMatch,omitempty"`
	Change      *RouteFilterRulesChange `json:"change,omitempty"`
	Action      string                  `json:"action,omitempty"`
	Prefix      string                  `json:"prefix,omitempty"`
	Changelog   *Changelog              `json:"changelog,omitempty"`
}
