/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// PortState : Port lifecycle state
type PortState string

// List of PortState
const (
	PENDING_PortState        PortState = "PENDING"
	PROVISIONING_PortState   PortState = "PROVISIONING"
	PROVISIONED_PortState    PortState = "PROVISIONED"
	ACTIVE_PortState         PortState = "ACTIVE"
	DEPROVISIONING_PortState PortState = "DEPROVISIONING"
	DEPROVISIONED_PortState  PortState = "DEPROVISIONED"
	INACTIVE_PortState       PortState = "INACTIVE"
	FAILED_PortState         PortState = "FAILED"
	ADDED_PortState          PortState = "ADDED"
	DELETED_PortState        PortState = "DELETED"
	TO_BE_ADDED_PortState    PortState = "TO_BE_ADDED"
	TO_BE_DELETED_PortState  PortState = "TO_BE_DELETED"
)
