/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// ModelType : type of events
type ModelType string

// List of Type
const (
	TRANSACTION_STATUS_AUDIT_ModelType ModelType = "TRANSACTION_STATUS_AUDIT"
	RP_OPSTATUS_NOTIFICATION_ModelType ModelType = "RP_OPSTATUS_NOTIFICATION"
)
