/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// EPT Service Package Information
type PrecisionTimePackageResponse struct {
	Href                 string     `json:"href,omitempty"`
	Code                 string     `json:"code"`
	Type_                string     `json:"type,omitempty"`
	Bandwidth            int32      `json:"bandwidth,omitempty"`
	ClientsPerSecondMax  int32      `json:"clientsPerSecondMax,omitempty"`
	RedundancySupported  bool       `json:"redundancySupported,omitempty"`
	MultiSubnetSupported bool       `json:"multiSubnetSupported,omitempty"`
	AccuracyUnit         string     `json:"accuracyUnit,omitempty"`
	AccuracySla          int32      `json:"accuracySla,omitempty"`
	AccuracyAvgMin       int32      `json:"accuracyAvgMin,omitempty"`
	AccuracyAvgMax       int32      `json:"accuracyAvgMax,omitempty"`
	Changelog            *Changelog `json:"changelog,omitempty"`
}
