/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// Route Filter change operation data
type RouteFilterRulesChangeOperation struct {
	// name of  route filter rule
	Name string `json:"name"`
	// cust provided description
	Description string `json:"description,omitempty"`
	// type of filter rule
	Type_ string `json:"type"`
	// given prefix (does not change)
	Prefix string `json:"prefix"`
	// change to be made
	Action string `json:"action"`
}
