/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

import (
	"time"
)

// BGP IPv4 or IPv6 Connection State operational data
type BgpConnectionOperation struct {
	// BGP IPv4 or IPv6 Connection State operational status
	OperationalStatus string `json:"operationalStatus,omitempty"`
	// Last BGP State Update by Date and Time
	OpStatusChangedAt time.Time `json:"opStatusChangedAt,omitempty"`
}
